
Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos| 
    centos.vm.box = "centos/7"

    centos.vm.network "forwarded_port", guest: 80, host: 8080

    centos.vm.provider "virtualbox" do |vb|
    
    #Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.cpus = "2"
    end

      centos.vm.provision "shell", inline: <<-SHELL
      #sudo yum update -y
      sudo yum install httpd -y
      sudo systemctl start httpd.service
      sudo systemctl enable httpd.service
    SHELL
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"

    ubuntu.vm.provider "virtualbox" do |vb|
    
    #Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

 
end
