
Vagrant.configure("2") do |config|
  config.vm.provision "file", source: "Dockerfile", destination: "$HOME/vagrant/"
  
  config.vm.provision "shell", path: "script.sh"
  
#vagrant provision --provision-with file

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network "forwarded_port", guest: 8090, host: 8080
    ubuntu.vm.network "forwarded_port", guest: 3306, host: 3306, protocol: "tcp"
    #database connection works with: mysql -h localhost --protocol tcp -uroot -p'123456' -e 'SHOW DATABASES;'
    ubuntu.vm.provider "virtualbox" do |vb|
    
    #Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.cpus = "2"
    end
    
    
  end

 
end
